### PR TITLE
Decouple logical decoding and AVRO format.

### PR DESCRIPTION
**Pull request by a1exsh**
Provides for different output formats that can be chosen by the
connecting client using plugin options in the start command:

  START_REPLICATION SLOT \<slot\> LOGICAL \<XXX/XXX\> (FORMAT '\<format\>')

If not specified, AVRO is used as the default output format.

### CODE REVIEW

**Comment by a1exsh** [comment]
The intent is to add JSON output format using existing infrastructure.

**Comment by ept** [comment]
Interesting, thanks. Just wondering, did you also consider keeping the data encoding in the logical decoding plugin as Avro, and only doing the conversion to JSON in the client?

I am generally keen to keep the amount of code in the logical decoding plugin and extension as small as possible, since that reduces the surface area for bugs (and we want to be pretty sure that we're not going to segfault the Postgres server). Making the encoding customisable adds quite a bit of complexity and new ways how things can go wrong.

So if it's reasonably possible to do the conversion in the client, I'd prefer to do it that way.

**Comment by a1exsh** [comment]
Well, the JSON type has the advantage that you can just abuse postgres backend's json functions to produce it, thus greatly reducing the possibilities for bugs in the plugin's code itself.  The obvious disadvantage is  that you repeat the keys/schema with every message, but that's why the option to choose the preferred format.

I don't believe this patch adds intolerable amount of code and it only touches roughly 5% of the existing LOC.  And after that, adding more output formats doesn't constitute a major hazard for established code IMO, since it should be expected that one format is used consistently across postgres cluster n instead of all of them at the same time.

**Comment by ept** [comment]
@a1exsh Sorry for the delay, I've only just had a chance to review this. The code looks nice, but I have some questions about the overall approach.

As it stands, if you put the logical decoding output plugin in JSON mode, you can't use it with the Bottled Water client (you'd have to use `pg_recvlogical` or write your own client). In particular, you don't get the consistent snapshot coordinated with the change stream, which (for me) is one of the main goals of Bottled Water. So if all you want is a logical decoding plugin that generates JSON, that could just as well be a separate project.

However, I can see the value of JSON for people who don't want to use Avro as their application data model. For those use cases, it would be good to have both the consistent snapshot and the change stream encoded as JSON, and for the BW client to fully support this mode (eg command-line option). For this use case, I propose keeping Avro as the framing protocol (what is currently the outer layer of Avro in BW) and offering JSON as encoding for row-level data (currently the inner layer of Avro in BW).

Does that make sense? If you want to take that approach, the decoding plugin would need to be changed to use the Avro framing protocol, and JSON encoding would need to be added to the Snapshot export. It should be quite doable, and I think this would be a good way to proceed. What do you think?

**Comment by ept** [comment]
To be clear, the Avro framing protocol is used only for communication between the PG extension and the BW client, and not sent to Kafka. Any applications consuming from Kafka would only see JSON.

**Comment by a1exsh** [comment]
@ept thank you for the feedback!

Lately I was working on this to add support for export in JSON format (and I did find that pg_recvlogical works great for testing purposes): https://github.com/a1exsh/bottledwater-pg/tree/feature/json-smallest-workable

As I tend to see it, there is no benefit in wrapping JSON data in Avro frame: it's just an extra dependency both on server and client side.  And we are going to build another client anyway, because we're not sure if we really want to use kafka, or something else.

The intent currently is to add logical replication support to psycopg2 and write a generic client in Python, which would not be tied to JSON/Avro or kafka in any way.  Given the potential simplicity of Python client (see https://github.com/psycopg/psycopg2/pull/322/files#diff-6a98d00d2099e158ccce878ca6c97eeeR239) we expect to be able to experiment with different formats and storage systems more easily than adding such support to the existing C-based bottledwater clients.

We'll see how this works out. :-)

**Comment by ept** [comment]
@a1exsh Great to catch up in Berlin!

For anyone else following along with this thread, Oleksandr and I talked about this offline. Everyone agrees that JSON support in Bottled Water would be a good thing. As described in the last comment, he is exploring getting Postgres change data without a dependency on Avro or Kafka, and using a Python client instead of BW's C client.

I'm very interested to see how this works out. I think the best plan for now is for @a1exsh to continue experimenting freely, and figure out what works for his use cases. When that is done, let's figure out how to combine his work and Bottled Water. It would be nice for BW to work with the Python client (and potentially future clients in other languages), for which we'd have to agree on a common protocol. But I think that will best be figured out when @a1exsh's work has progressed further.

For now, I'll close this pull request, as the JSON support in the logical decoding plugin won't work with the current BW client. I may adapt some of the code to use JSON within BW's Avro-based framing protocol, but that'll be a separate PR — I've opened issue #15 for that. We can always revisit this later, when we've learnt more about what a good protocol should look like.

Thanks for developing this code further — it's great to see it evolving!

**Pull request closed without merging**
