### PR TITLE
Add free 'key' value inside send_kafka_message to avoid memory leak

### PR DESCRIPTION
**Pull request by badboyd**
In send_kafka_msg, it seems that rdkafka doesn't free the payload (it is 'val' in our situation ) when it is done with the payload. That why I propose that we change from RD_KAFKA_MSG_F_FREE to RD_KAFKA_MSG_F_COPY. Then we manually free val and key.

### CODE REVIEW

**Comment by badboyd** [comment]
@samstokes Could you check it ?

**Comment by badboyd** [comment]
[clabot:check]

**Comment by samstokes** [comment]
Hi @badboyd, thanks for contributing this patch!  However, I'm not sure I completely understand what you mean by "rdkafka doesn't free the payload".

My understanding is that when we pass `RD_KAFKA_MSG_F_FREE` to `rd_kafka_produce`, that instructs librdkafka to free the payload when it is done with it - [per docs in rdkafka.h](https://github.com/edenhill/librdkafka/blob/0ff40cc08bc6c3ba35cc5205c91131618a58a0c7/src/rdkafka.h#L2093-L2094).

Are you saying that you have observed that rdkafka does not in fact free the payload, despite our passing this flag?  If so, it might be better to file a bug against rdkafka, in case this problem is fixed in a later version.

Or am I missing something else that we should be doing? :)

**Comment by badboyd** [comment]
Thanks @samstokes for the reply. I've read the [docs](https://github.com/edenhill/librdkafka/blob/0ff40cc08bc6c3ba35cc5205c91131618a58a0c7/src/rdkafka.h#L2093-L2094) too, but I have observed that rdkafka does not in fact free the payload when we use `RD_KAFKA_MSG_F_FREE` flag.

**Comment by samstokes** [comment]
Sorry for the slow response.  Could you give a bit more information about the problem you are seeing, and how you can tell that the payload is not being freed?  e.g. are you seeing Bottled Water's memory usage increasing as it streams updates?  In that case, it would be useful to know more about the database you are streaming (number of rows, size of schema), and roughly how many bytes it grows by per row.

I'd like to be cautious making changes to the memory management logic because there's been at least one other memory leak reported (#83), and we don't yet know what's causing it, or whether it's specific to the recently-added JSON support or occurs in all cases.  If `RD_KAFKA_MSG_F_FREE` is not working as advertised, then we'd have a problem in all cases (and moreover we should report the bug to rdkafka).

**Comment by samstokes** [comment]
@badboyd I finally got a chance to dig into this and I've reproduced the leak you observed, which I think is the same leak as was reported in #83.  I think it's not actually the payload (`val`) that we're leaking, but the `key`: `rd_kafka_produce` takes the key as a `const void *` pointer, indicating it doesn't intend to free it, and internally it always takes a copy of the key.  So I think `RD_KAFKA_MSG_F_FREE` is actually working as advertised, and freeing the payload correctly, but we're mistakenly relying on it to free the key as well, which it never promised to do :)

So your patch does fix the memory leak, which is awesome - thanks for reporting and contributing this!

I'd love to merge your Pull Request.  First there are a couple of small changes that I think would improve it:

 * I'd prefer to keep `RD_KAFKA_MSG_F_FREE` (rather than `_COPY`) for freeing the payload, since the message payload could be quite large (e.g. a table with many columns, or a row with a large text field), so copying it could be slow.  In that case the only change we need is to explicitly free the key.

 * The commit message would be better if it described the reason for the change - e.g. a description of the memory leak that was occurring and why this change fixes it - rather than which file was changed (which you can tell from git anyway).  That will help other developers in the future to understand the code more easily, since they can read the history and see why the code was changed.  Would you mind updating the commit message (and the title of the pull request)?  You should be able to edit the message by checking out this branch and running `git commit --amend`.  (Then you will need to `git push --force` to get Github to accept the updated branch.)

Then I'll happily merge this!

**Comment by badboyd** [comment]
Thanks @samstokes for your reply, I've added a new commit, please check it.

**Comment by samstokes** [comment]
Fantastic, thanks very much!

**Pull request merged**
